/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AppThreatsRouteImport } from './routes/_app.threats'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppIntelRouteImport } from './routes/_app.intel'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommandRouteImport } from './routes/_app.command'
import { Route as AppAssessmentsRouteImport } from './routes/_app.assessments'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppThreatsRoute = AppThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelRoute = AppIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/assessments': typeof AppAssessmentsRoute
  '/command': typeof AppCommandRoute
  '/dashboard': typeof AppDashboardRoute
  '/intel': typeof AppIntelRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/threats': typeof AppThreatsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/assessments': typeof AppAssessmentsRoute
  '/command': typeof AppCommandRoute
  '/dashboard': typeof AppDashboardRoute
  '/intel': typeof AppIntelRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/threats': typeof AppThreatsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/assessments': typeof AppAssessmentsRoute
  '/_app/command': typeof AppCommandRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/intel': typeof AppIntelRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/threats': typeof AppThreatsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assessments'
    | '/command'
    | '/dashboard'
    | '/intel'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/threats'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assessments'
    | '/command'
    | '/dashboard'
    | '/intel'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/threats'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/alerts'
    | '/_app/assessments'
    | '/_app/command'
    | '/_app/dashboard'
    | '/_app/intel'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/threats'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/threats': {
      id: '/_app/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof AppThreatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intel': {
      id: '/_app/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof AppIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command': {
      id: '/_app/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments': {
      id: '/_app/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppCommandRoute: typeof AppCommandRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntelRoute: typeof AppIntelRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppThreatsRoute: typeof AppThreatsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppCommandRoute: AppCommandRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntelRoute: AppIntelRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppThreatsRoute: AppThreatsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
